# Generated by Django 4.0.2 on 2022-02-28 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_seathistory_filled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seathistory',
            name='filled_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='seathistory',
            name='vacant_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
